<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.6">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Liena Lesniece">

<title>Bjørnar’s assignment in Gretl – OEKA201AssignmentLL</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-6c21014d9765ba549c6ebad95917e4d7.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-59731d394be66c1e6c8bf119cb58801b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">OEKA201AssignmentLL</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Index</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./assignment_gretl.html" aria-current="page"> 
<span class="menu-text">Exercises using Gretl</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./assignment_r.html"> 
<span class="menu-text">Exercises using R</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#exercise-1" id="toc-exercise-1" class="nav-link active" data-scroll-target="#exercise-1">Exercise 1</a></li>
  <li><a href="#exercise-2" id="toc-exercise-2" class="nav-link" data-scroll-target="#exercise-2">Exercise 2</a></li>
  <li><a href="#exercise-3" id="toc-exercise-3" class="nav-link" data-scroll-target="#exercise-3">Exercise 3</a></li>
  <li><a href="#exercise-4" id="toc-exercise-4" class="nav-link" data-scroll-target="#exercise-4">Exercise 4</a></li>
  <li><a href="#exercise-5" id="toc-exercise-5" class="nav-link" data-scroll-target="#exercise-5">Exercise 5</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="assignment_gretl.docx"><i class="bi bi-file-word"></i>MS Word</a></li><li><a href="assignment_gretl.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li><li><a href="assignment_gretl.epub"><i class="bi bi-file"></i>ePub</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Bjørnar’s assignment in Gretl</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Liena Lesniece </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Høgskolen i Østfold
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<p><a href="https://hiof.instructure.com/courses/9596/files/folder/Assignment?preview=1695176">Bjørnar’s assignment</a></p>
<section id="exercise-1" class="level2">
<h2 class="anchored" data-anchor-id="exercise-1">Exercise 1</h2>
<pre><code>﻿                   Mean     Median       S.D.        Min        Max
price              1406       1080       1027      495.2       4884
WinterRain        608.4      600.0      129.0      376.0      830.0
temp              16.48      16.42     0.6592      14.98      17.65
HarvestRain       144.8      123.0      73.07      38.00      292.0
Age               16.19      16.00      8.246      3.000      31.00
</code></pre>
<p>A case of wine has an average market <strong>price</strong> of 1,406, a median of 1,080, and a standard deviation of 1,027. 495.2 is the lowest price that has been determined, while 4884 is the highest. This comparatively high standard deviation indicates significant price volatility for wines, which is probably caused by a mix of aging, climate, and vintage quality.</p>
<p>Before the growing season, the average amount of <strong>WinterRain</strong> (October–March) is 608.4 mm, with a median of 600 mm and a standard deviation of 129 mm. It varies slightly between vintages, with values ranging from 376 mm to 830 mm.</p>
<p>With a mean <strong>temperature</strong> of 16.48°C and a standard deviation of 0.66°C, the growth season temperature (April–September) is mainly constant throughout the sample. The estimated temperatures range from a minimum of 14.98°C to a maximum of 17.65°C.</p>
<p>There is a higher volatility in <strong>HarvestRain</strong> (August–September), with a mean of 144.8 mm, a standard deviation of 73.07 mm, and a range of 38 mm to 292 mm. This variation raises the possibility that some vintages had unusually wet harvest seasons, which could affect the quality of the grapes.</p>
<p>With a mean of 16.19 years and a standard deviation of 8.25 years, the wine’s <strong>age</strong> in 1983 varied from 3 to 31 years. With a median age of 16, the distribution appears to be pretty symmetrical.</p>
<p>In summary, the data show that wine pricing and environment variables fluctuate significantly, while age and temperature are more evenly balanced.</p>
</section>
<section id="exercise-2" class="level2">
<h2 class="anchored" data-anchor-id="exercise-2">Exercise 2</h2>
<p><em>Model 1</em> <span class="math display">\[
price_i = \beta_0 + \beta_1Age_i + u_i
\]</span></p>
<p><strong>a.</strong></p>
<pre><code>﻿Model 1: OLS, using observations 1952-1980 (T = 27)
Missing or incomplete observations dropped: 2
Dependent variable: price

             coefficient   std. error   t-ratio   p-value
  -------------------------------------------------------
  const       494.278       402.112      1.229    0.2304 
  Age          56.3183       22.2218     2.534    0.0179  **

Mean dependent var   1405.800   S.D. dependent var   1027.226
Sum squared resid    21827151   S.E. of regression   934.3907
R-squared            0.204406   Adjusted R-squared   0.172582
F(1, 25)             6.423065   P-value(F)           0.017902
Log-likelihood      −221.9495   Akaike criterion     447.8990
Schwarz criterion    450.4907   Hannan-Quinn         448.6697

Warning: The version of this datafile (1.5) is higher than that fully
supported by this build of gretl (1.4). Some features may not be
correctly recognized.
</code></pre>
<p><strong>b.</strong></p>
<p><span class="math display">\[
\widehat{\text{price}} = 494.28 + 56.32 \cdot \text{Age}
\]</span> If the age increases by one year, we expect the price of the wine which is 494.278 to increase by 56.3183 per year.</p>
<p><strong>c.</strong></p>
<p>Test wheather Age has a significant effect on Price by looking at:</p>
<ul>
<li>Null hypothesis (<span class="math inline">\(H_0\)</span>): <span class="math inline">\(\beta_{\text{Age}} = 0\)</span> (no effect)</li>
<li>Alternative hypothesis (<span class="math inline">\(H_1\)</span>): <span class="math inline">\(\beta_{\text{Age}} \neq 0\)</span> (significant effect)</li>
</ul>
<p>At the <span class="math inline">\(\alpha = 0.01\)</span> level, we reject <span class="math inline">\(H_0\)</span> if: <span class="math display">\[
p-value &lt; 0.01
\]</span> Since the p-value is 0.0179 &gt; 0.01, we fail to reject the null hypothesis at the 1% level.</p>
<p>The Age coefficient does not achieve significance at the more restrictive 1% level, despite being significant at the 5% level. As a result, we make the conclusion that there is not enough data to support that wine age significantly affects pricing at the 1% level.</p>
<p><strong>d.</strong></p>
<p>We use <span class="math inline">\(Model\)</span> <span class="math inline">\(1\)</span>:</p>
<p><span class="math display">\[
\widehat{\text{price}} = 494.28 + 56.32 \cdot \text{Age}
\]</span></p>
<p>We calculate predicted wine prices for three values of the variable Age: the minimum of 3, the mean of 16.19, and the maximum of 31, based on the output from gretl in exercise 1.</p>
<p>When Age = 3, the predicted wine price is approximately 663.24.</p>
<p>When Age = 16.19, the predicted price is approximately 1406.1, which is very close to the mean price in the output which is 1405.8.</p>
<p>When Age = 31, the predicted price increases to approximately 2240.2.</p>
<p>These results demonstrate the positive correlation between price and age that the regression model suggests, that the wine’s expected market value increases linearly with age.</p>
<p><strong>e.</strong></p>
<p>Since the prices were measured in 1983, the wine from 1961 is: <span class="math display">\[
Age=1983−1961=22
\]</span> Then we will calculate the predicted price for Age = 22: <span class="math display">\[
\widehat{\text{price}} = 494.28 + 56.32 \cdot \ 22 = 1733.32
\]</span> Then we look at the degrees of freedom: <span class="math display">\[
df=n−k−1=27−1−1=25
\]</span> From a standard t-table, with 25 degrees of freedom, the critical t-value at 95% confidence is 2.060.</p>
<p>The margin of error: <span class="math display">\[
t⋅SE=2.060\cdot \ 934.39=1924.85
\]</span> Interval: <span class="math display">\[
Lowest Range = 1733−1924.85=−191.53
\]</span> <span class="math display">\[
Highest Range = 1733.32+1924.85=3658.17
\]</span> The 95% prediction interval is [−191.53, 3658.17]</p>
</section>
<section id="exercise-3" class="level2">
<h2 class="anchored" data-anchor-id="exercise-3">Exercise 3</h2>
<p><em>Model 2</em> <span class="math display">\[
price_i = \beta_0 + \beta_1Age_i + \beta_2WinterRain_i  +\beta_3temp_i + \beta_3HarvestRain_i + u_i
\]</span></p>
<p><strong>a.</strong></p>
<pre><code>﻿Model 2: OLS, using observations 1952-1980 (T = 27)
Missing or incomplete observations dropped: 2
Dependent variable: price

                coefficient    std. error    t-ratio   p-value 
  -------------------------------------------------------------
  const         −15509.0       3379.87       −4.589    0.0001   ***
  Age               39.2126      14.3490      2.733    0.0121   **
  WinterRain         2.75098      0.965119    2.850    0.0093   ***
  temp             930.787      190.557       4.885    6.97e-05 ***
  HarvestRain       −5.04694      1.61682    −3.122    0.0050   ***

Mean dependent var   1405.800   S.D. dependent var   1027.226
Sum squared resid     7238994   S.E. of regression   573.6246
R-squared            0.736141   Adjusted R-squared   0.688166
F(4, 22)             15.34443   P-value(F)           3.93e-06
Log-likelihood      −207.0499   Akaike criterion     424.0999
Schwarz criterion    430.5791   Hannan-Quinn         426.0265
</code></pre>
<p><strong>b.</strong> <span class="math display">\[
\widehat{\text{price}} = -15{,}509.0 + 39.21 \cdot \text{Age} + 2.75 \cdot \text{WinterRain} + 930.79 \cdot \text{temp} - 5.05 \cdot \text{HarvestRain}
\]</span> - If the <strong>Age</strong> of the wine increases by one year, we expect the price of the wine, which is initially predicted to be −15,509.0, to increase by <strong>39.21 per year</strong>.</p>
<ul>
<li><p>If <strong>WinterRain</strong> increases by 1, we expect the price of the wine to increase by <strong>2.75</strong>.</p></li>
<li><p>If the <strong>temperature</strong> during the growing season increases by 1°C, we expect the price of the wine to increase by <strong>930.79</strong>.</p></li>
<li><p>If <strong>HarvestRain</strong> increases by 1, we expect the price of the wine to <strong>decrease by 5.05</strong>.</p></li>
</ul>
<p><strong>c.</strong></p>
<p>Exercise 3 multiple regression model provides a much better fit than Exercise 2 basic regression model. The expanded model explains a greater amount of the variation in wine prices, as shown by the R-squared rising from 0.204 to 0.736. The regression’s standard error drops from 934.39 to 573.62, indicating that predictions are now more accurate.</p>
<p>When the weather variables are included, the coefficient for age drops from 56.32 to 39.21, but it is still statistically significant. This decrease raises the possibility that the basic model overemphasized the impact of age since some variables were left out. The multiple regression model offers a more precise and trustworthy examination of the elements influencing wine pricing by incorporating the other variables.</p>
</section>
<section id="exercise-4" class="level2">
<h2 class="anchored" data-anchor-id="exercise-4">Exercise 4</h2>
<p><em>Model 3</em> <span class="math display">\[
price_i = \beta_0 + \beta_1Dheavyraint_i + \beta_2tempt_i + \beta_3temp_i · Dheavyrain_i + u_i
\]</span></p>
<p><strong>a.</strong></p>
<pre><code>﻿Model 3: OLS, using observations 1952-1980 (T = 27)
Missing or incomplete observations dropped: 2
Dependent variable: price

                coefficient   std. error   t-ratio   p-value
  ----------------------------------------------------------
  const         −16289.5       4395.18     −3.706    0.0012  ***
  Dheavyrain     11634.1       8990.38      1.294    0.2085 
  temp            1082.95       266.391     4.065    0.0005  ***
  temp_Dheavy     −756.902      546.064    −1.386    0.1790 

Mean dependent var   1405.800   S.D. dependent var   1027.226
Sum squared resid    14038659   S.E. of regression   781.2660
R-squared            0.488295   Adjusted R-squared   0.421550
F(3, 23)             7.315911   P-value(F)           0.001294
Log-likelihood      −215.9914   Akaike criterion     439.9829
Schwarz criterion    445.1662   Hannan-Quinn         441.5242

Excluding the constant, p-value was highest for variable 6 (Dheavyrain)
</code></pre>
<p><strong>b.</strong></p>
<p><span class="math display">\[
\widehat{\text{price}} = -16{,}289.5 + 11{,}634.1 \cdot \text{Dheavyrain} + 1082.95 \cdot \text{temp} - 756.90 \cdot (\text{temp} \cdot \text{Dheavyrain})
\]</span> The consistent effect of heavy HarvestRain is captured by the variable Dheavyrain. Although its coefficient 11634.1 indicates that the expected base price is greater in years with extremely high HarvestRain, this effect is not statistically significant (p = 0.2085), therefore we are unable to draw firm conclusions about the impact of rain alone.</p>
<p>With a coefficient of -756.90, the interaction term temp_Dheavyrain shows that the price-boosting impact of temperature is less pronounced in years with high rain. This interaction implies that heavy rain lessens the value of warm growing seasons, most likely because of lower grape quality at harvest, even if it is also not statistically significant (p = 0.1790).</p>
</section>
<section id="exercise-5" class="level2">
<h2 class="anchored" data-anchor-id="exercise-5">Exercise 5</h2>
<ol type="a">
<li><span class="math display">\[
Residual=Actual Price −Predicted Price
\]</span> <span class="math display">\[
ActualPrice = 4883.903
\]</span> Next we determine each model’s expected price and residual.</li>
</ol>
<p><em>Model 1</em> – Simple regression <span class="math display">\[
\widehat{\text{price}} = 494.28 + 56.32 \cdot 22 = 1733.32
\]</span> <span class="math display">\[Residual = 4883.903 − 1733.32 = 3150.58\]</span></p>
<p><em>Model 2</em> – Multiple regression <span class="math display">\[
\widehat{\text{price}} = -15509.0 + 39.21 \cdot 22 + 2.75 \cdot 830 + 930.79 \cdot 17.3333 - 5.05 \cdot 38
\]</span> <span class="math display">\[
\widehat{\text{price}} = -15509.0 + 862.62 + 2282.5 + 16133.66 - 191.9 = 3577.88
\]</span> <span class="math display">\[Residual = 4883.903 − 3577.88 = 1306.023\]</span> <em>Model 3</em> -Dummy regression <span class="math display">\[
\widehat{\text{price}} = -16{,}289.5 + 11{,}634.1 \cdot \text{Dheavyrain} + 1082.95 \cdot \text{temp} - 756.90 \cdot \text{temp} \cdot \text{Dheavyrain}
\]</span> <span class="math display">\[
\widehat{\text{price}} = -16{,}289.5 + 11{,}634.1 \cdot 0 + 1082.95 \cdot 17.3333 - 756.90 \cdot 17.3333 \cdot 0 = 2481.6
\]</span> <span class="math display">\[Residual = 4883.903 − 2481.6 = 2402.303\]</span> <strong>b.</strong></p>
<p>With a residual of 1306.023, Model 2 (the multiple regression incorporating age and weather factors) appears to offer the best accurate prediction for the 1961 vintage, as opposed to 2402.303 for Model 3 and 3150.58 for Model 1. This suggests that Model 2 is the one that most closely resembles the 1961 vintage’s actual market price.</p>
<p>With an R-squared of 0.736, Model 2 has the strongest explanatory power outside of residual analysis, accounting for roughly 73.6% of the variation in wine prices. Compared to Model 1’s R-squared of 0.204 and Model 3’s R-squared of 0.488, this is much higher.</p>
<p>The Model 2’s standard error was the lowest of the three explanatory factors, and all four of them—Age, HarvestRain, WinterRain, and temperature—were statistically significant.</p>
<p>In conclusion, Model 2 is the best model for forecasting Bordeaux wine prices when taking into account both the predicted accuracy for the 1961 vintage and the overall model performance.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>